//1 - Exercício - Operações Matemáricas

let a = 10;
let b = 2;

let soma = a+b;
let subtracao = a-b;
let multiplicacao = a*b;
let divisao = a/b;
let resto = a%b;

console.log(`Soma:----------Para (a) igual a ${a} e (b) igual a ${b}, o resultado é: ${soma}`);
console.log(`Subtração:-----Para (a) igual a ${a} e (b) igual a ${b}, o resultado é: ${subtracao}`);
console.log(`Multiplicação:-Para (a) igual a ${a} e (b) igual a ${b}, o resultado é: ${multiplicacao}`);
console.log(`Divisão:-------Para (a) igual a ${a} e (b) igual a ${b}, o resultado é: ${divisao}`);
console.log(`Resto:---------Para (a) igual a ${a} e (b) igual a ${b}, o resultado é: ${resto}`);

